import { z, type ZodType } from 'zod'


import {
  connectorCaptureBatchSchema,
  connectorCaptureReceiptSchema,
  connectorGrantRequestSchema,
  connectorGrantSchema,
  connectorPublicOriginSchema,
} from '../connector/index.js'

import {
  adminSessionSchema,
  authorityRoleChangeRequestSchema,
  authorityRoleChangeResultSchema,
  currentMembershipConsentsSchema,
  currentMembershipSchema,
  membershipConsentSchema,
  membershipOnboardingRequestSchema,
  membershipOnboardingResultSchema,
  problemSchema,
} from './access.js'
import {
  addCollectionPlaceCommandSchema,
  browserCreatePrivateCollectionCommandSchema,
  browserLibraryCommandRequestSchema,
  browserCreatePrivateNoteCommandSchema,
  browserPrivateNoteCommandRequestSchema,
  browserUpdatePrivateNoteCommandSchema,
  browserVisitRecordRequestSchema,
  copyPublishedCollectionCommandSchema,
  createCollectionCommandSchema,
  createEntryCommandSchema,
  createNoteCommandSchema,
  createTagCommandSchema,
  deleteCollectionCommandSchema,
  deleteTagCommandSchema,
  libraryCommandRequestSchema,
  moveCollectionPlaceCommandSchema,
  publishedCollectionMapSchema,
  publishedCollectionSchema,
  publishedWritingSchema,
  removeCollectionPlaceCommandSchema,
  renameCollectionCommandSchema,
  renameTagCommandSchema,
  setCollectionPublicationCommandSchema,
  setPlacePreferencesCommandSchema,
  tagPlaceCommandSchema,
  untagPlaceCommandSchema,
  updateEntryCommandSchema,
  updateNoteCommandSchema,
  visitRecordRequestSchema,
  writingCommandRequestSchema,
} from './content.js'
import {
  placeImportBatchDetailSchema,
  placeImportBatchListSchema,
  placeImportBatchSchema,
  placeImportCancelRequestSchema,
  placeImportRequestSchema,
  placeImportResumeRequestSchema,
  placeImportReviewRequestSchema,
  placeImportReviewResultSchema,
  providerConnectionListSchema,
} from '../imports/index.js'
import {
  collectionLifecycleCommandRequestV2Schema,
  collectionLifecycleCommandResultV2Schema,
  collectionOrderCommandRequestV2Schema,
  collectionOrderCommandResultV2Schema,
  discoverableCollectionResponseV2Schema,
  libraryCommandResultSchema,
  libraryCollectionDetailResponseSchema,
  libraryCollectionListResponseSchema,
  libraryPlacePreferencesResponseSchema,
  libraryPlaceFacetsResponseSchema,
  libraryMapResponseSchema,
  libraryPlaceOrganizationResponseSchema,
  libraryPlaceListResponseSchema,
  libraryTagListResponseSchema,
  personalLibraryWorkspaceResponseV2Schema,
  placeFilingCommandRequestV2Schema,
  placeFilingCommandResultV2Schema,
  placeFilingResponseV2Schema,
  publicCollectionDirectoryResponseV2Schema,
  publishedCollectionCopyCommandRequestV2Schema,
  publishedCollectionCopyCommandResultV2Schema,
} from '../library/index.js'
import {
  placeDetailResponseSchema,
  publicPlaceDetailResponseSchema,
} from '../places/index.js'
import {
  publicProfileAppealQueueSchema,
  publicProfileAppealRequestSchema,
  publicProfileAppealResolutionRequestSchema,
  publicProfileAppealResolutionResultSchema,
  publicProfileAppealResultSchema,
  publicProfileCommandResultSchema,
  publicProfileModerationNoticesSchema,
  publicProfileModerationRecordSchema,
  publicProfileModerationRequestSchema,
  publicProfileModerationResultSchema,
  publicProfileProjectionSchema,
  publicProfileRecordSchema,
  publicProfileReportQueueSchema,
  publicProfileReportRequestSchema,
  publicProfileReportResultSchema,
  publicProfileNoticeAcknowledgementResultSchema,
  setPublicProfileRequestSchema,
} from '../profiles/index.js'
import {
  visitHistoryResponseSchema,
  visitRecordResultSchema,
  visitSummaryResponseSchema,
} from '../visits/index.js'
import {
  writingCommandResultSchema,
  writingDetailResponseSchema,
  writingListResponseSchema,
} from '../writing/index.js'
import {
  catalogPlaceSearchRequestSchema,
  catalogPlaceSearchResponseSchema,
  placeSearchRequestSchema,
  placeSearchResponseSchema,
  placeSuggestionMaterializationRequestSchema,
  placeSuggestionMaterializationResponseSchema,
  placeSuggestionSelectionRequestSchema,
  placeSuggestionSelectionResponseSchema,
  placeSuggestionsRequestSchema,
  placeSuggestionsResponseSchema,
  providerPlaceDetailRequestSchema,
  providerPlaceDetailSchema,
  taxonomyProjectionSchema,
} from '../search/index.js'
import {
  accountErasureReviewCommandRequestV2Schema,
  accountErasureReviewCommandResultV2Schema,
  connectorCaptureChunkReceiptV2Schema,
  connectorCaptureChunkV2Schema,
  connectorCaptureCompleteRequestV2Schema,
  connectorCaptureCompleteResultV2Schema,
  connectorCaptureManifestStatusV2Schema,
  connectorImportGrantRequestV2Schema,
  connectorImportGrantResultV2Schema,
  importPlanCommandRequestV2Schema,
  importPlanCommandResultV2Schema,
  importPlanV2Schema,
  outboundTransferCommandRequestV2Schema,
  outboundTransferCommandResultV2Schema,
  outboundTransferV2Schema,
  outboundExecutionAttemptReceiptV2Schema,
  outboundExecutionAttemptIntentReceiptV2Schema,
  outboundExecutionAttemptIntentV2Schema,
  outboundExecutionAttemptV2Schema,
  outboundExecutionAuthorizationReceiptV2Schema,
  outboundExecutionConsumeRequestV2Schema,
  outboundExecutionGrantRequestV2Schema,
  outboundExecutionGrantResultV2Schema,
  outboundExecutionReconciliationReceiptV2Schema,
  outboundExecutionReconciliationV2Schema,
  providerCapabilityListV2Schema,
  providerConnectionCommandRequestV2Schema,
  providerConnectionCommandResultV2Schema,
  providerConnectionListV2Schema,
  providerTargetListProjectionV2Schema,
  sourceSnapshotDetailV2Schema,
  sourceSnapshotListV2Schema,
  transferOperationCommandRequestV2Schema,
  transferOperationCommandResultV2Schema,
  transferOperationItemPageV2Schema,
  transferOperationListV2Schema,
  transferOperationSummaryV2Schema,
  transferOperationV2Schema,
} from '../transfers/index.js'
import { processStatusSchema } from './system.js'

import { ref } from './openapi/model.js'
import { accessAndCommunityPaths } from './openapi/paths/access-and-community.js'
import { importPaths } from './openapi/paths/imports.js'
import { libraryPaths } from './openapi/paths/library.js'
import { placeContentPaths } from './openapi/paths/place-content.js'
import { searchPaths } from './openapi/paths/search.js'
import { systemAndBrowserPaths } from './openapi/paths/system-and-browser.js'
import { transferOpenApiPaths } from './openapi/paths/transfers.js'

const paths = {
  ...systemAndBrowserPaths,
  ...accessAndCommunityPaths,
  ...importPaths,
  ...libraryPaths,
  ...placeContentPaths,
  ...searchPaths,
  ...transferOpenApiPaths,
}

const schemas: Readonly<Record<string, ZodType>> = {
  ProcessStatus: processStatusSchema,
  AdminSession: adminSessionSchema,
  ConnectorPublicOrigin: connectorPublicOriginSchema,
  ConnectorGrantRequest: connectorGrantRequestSchema,
  ConnectorGrant: connectorGrantSchema,
  ConnectorCaptureBatch: connectorCaptureBatchSchema,
  ConnectorCaptureReceipt: connectorCaptureReceiptSchema,
  LibraryCommandRequest: libraryCommandRequestSchema,
  BrowserLibraryCommandRequest: browserLibraryCommandRequestSchema,
  LibraryCommandResult: libraryCommandResultSchema,
  LibraryPlacePreferences: libraryPlacePreferencesResponseSchema,
  ProviderConnectionList: providerConnectionListSchema,
  PlaceImportRequest: placeImportRequestSchema,
  PlaceImportBatch: placeImportBatchSchema,
  PlaceImportBatchList: placeImportBatchListSchema,
  PlaceImportBatchDetail: placeImportBatchDetailSchema,
  PlaceImportCancelRequest: placeImportCancelRequestSchema,
  PlaceImportResumeRequest: placeImportResumeRequestSchema,
  PlaceImportReviewRequest: placeImportReviewRequestSchema,
  PlaceImportReviewResult: placeImportReviewResultSchema,
  SetPlacePreferencesCommand: setPlacePreferencesCommandSchema,
  CreateCollectionCommand: createCollectionCommandSchema,
  BrowserCreatePrivateCollectionCommand: browserCreatePrivateCollectionCommandSchema,
  AddCollectionPlaceCommand: addCollectionPlaceCommandSchema,
  RenameCollectionCommand: renameCollectionCommandSchema,
  SetCollectionPublicationCommand: setCollectionPublicationCommandSchema,
  DeleteCollectionCommand: deleteCollectionCommandSchema,
  RemoveCollectionPlaceCommand: removeCollectionPlaceCommandSchema,
  MoveCollectionPlaceCommand: moveCollectionPlaceCommandSchema,
  CreateTagCommand: createTagCommandSchema,
  TagPlaceCommand: tagPlaceCommandSchema,
  RenameTagCommand: renameTagCommandSchema,
  DeleteTagCommand: deleteTagCommandSchema,
  UntagPlaceCommand: untagPlaceCommandSchema,
  CopyPublishedCollectionCommand: copyPublishedCollectionCommandSchema,
  VisitRecordRequest: visitRecordRequestSchema,
  BrowserVisitRecordRequest: browserVisitRecordRequestSchema,
  BrowserCreatePrivateNoteCommand: browserCreatePrivateNoteCommandSchema,
  BrowserUpdatePrivateNoteCommand: browserUpdatePrivateNoteCommandSchema,
  BrowserPrivateNoteCommandRequest: browserPrivateNoteCommandRequestSchema,
  VisitRecordResult: visitRecordResultSchema,
  VisitSummaryResponse: visitSummaryResponseSchema,
  WritingCommandRequest: writingCommandRequestSchema,
  WritingCommandResult: writingCommandResultSchema,
  CreateNoteCommand: createNoteCommandSchema,
  UpdateNoteCommand: updateNoteCommandSchema,
  CreateEntryCommand: createEntryCommandSchema,
  UpdateEntryCommand: updateEntryCommandSchema,
  CurrentMembership: currentMembershipSchema,
  MembershipConsent: membershipConsentSchema,
  MembershipOnboardingRequest: membershipOnboardingRequestSchema,
  CurrentMembershipConsents: currentMembershipConsentsSchema,
  MembershipOnboardingResult: membershipOnboardingResultSchema,
  AuthorityRoleChangeRequest: authorityRoleChangeRequestSchema,
  AuthorityRoleChangeResult: authorityRoleChangeResultSchema,
  PublishedCollection: publishedCollectionSchema,
  PublishedCollectionMap: publishedCollectionMapSchema,
  PublishedWriting: publishedWritingSchema,
  LibraryPlaceListResponse: libraryPlaceListResponseSchema,
  LibraryPlaceFacetsResponse: libraryPlaceFacetsResponseSchema,
  LibraryMapResponse: libraryMapResponseSchema,
  LibraryPlaceOrganizationResponse: libraryPlaceOrganizationResponseSchema,
  LibraryCollectionListResponse: libraryCollectionListResponseSchema,
  LibraryCollectionDetailResponse: libraryCollectionDetailResponseSchema,
  LibraryTagListResponse: libraryTagListResponseSchema,
  PersonalLibraryWorkspaceV2: personalLibraryWorkspaceResponseV2Schema,
  PlaceFilingV2: placeFilingResponseV2Schema,
  PlaceFilingCommandRequestV2: placeFilingCommandRequestV2Schema,
  PlaceFilingCommandResultV2: placeFilingCommandResultV2Schema,
  CollectionOrderCommandRequestV2: collectionOrderCommandRequestV2Schema,
  CollectionOrderCommandResultV2: collectionOrderCommandResultV2Schema,
  CollectionLifecycleCommandRequestV2: collectionLifecycleCommandRequestV2Schema,
  CollectionLifecycleCommandResultV2: collectionLifecycleCommandResultV2Schema,
  PublicCollectionDirectoryV2: publicCollectionDirectoryResponseV2Schema,
  DiscoverableCollectionV2: discoverableCollectionResponseV2Schema,
  PublishedCollectionCopyCommandRequestV2: publishedCollectionCopyCommandRequestV2Schema,
  PublishedCollectionCopyCommandResultV2: publishedCollectionCopyCommandResultV2Schema,
  VisitHistoryResponse: visitHistoryResponseSchema,
  WritingListResponse: writingListResponseSchema,
  WritingDetailResponse: writingDetailResponseSchema,
  PlaceDetail: placeDetailResponseSchema,
  PublicPlaceDetailResponse: publicPlaceDetailResponseSchema,
  PublicProfileRecord: publicProfileRecordSchema,
  SetPublicProfileRequest: setPublicProfileRequestSchema,
  PublicProfileCommandResult: publicProfileCommandResultSchema,
  PublicProfileProjection: publicProfileProjectionSchema,
  PublicProfileReportRequest: publicProfileReportRequestSchema,
  PublicProfileReportResult: publicProfileReportResultSchema,
  PublicProfileReportQueue: publicProfileReportQueueSchema,
  PublicProfileModerationRequest: publicProfileModerationRequestSchema,
  PublicProfileModerationRecord: publicProfileModerationRecordSchema,
  PublicProfileModerationResult: publicProfileModerationResultSchema,
  PublicProfileModerationNotices: publicProfileModerationNoticesSchema,
  PublicProfileNoticeAcknowledgementResult: publicProfileNoticeAcknowledgementResultSchema,
  PublicProfileAppealRequest: publicProfileAppealRequestSchema,
  PublicProfileAppealResult: publicProfileAppealResultSchema,
  PublicProfileAppealQueue: publicProfileAppealQueueSchema,
  PublicProfileAppealResolutionRequest: publicProfileAppealResolutionRequestSchema,
  PublicProfileAppealResolutionResult: publicProfileAppealResolutionResultSchema,
  PlaceSearchRequest: placeSearchRequestSchema,
  PlaceSearchResponse: placeSearchResponseSchema,
  CatalogPlaceSearchRequest: catalogPlaceSearchRequestSchema,
  CatalogPlaceSearchResponse: catalogPlaceSearchResponseSchema,
  PlaceSuggestionsRequest: placeSuggestionsRequestSchema,
  PlaceSuggestionsResponse: placeSuggestionsResponseSchema,
  PlaceSuggestionSelectionRequest: placeSuggestionSelectionRequestSchema,
  PlaceSuggestionSelectionResponse: placeSuggestionSelectionResponseSchema,
  PlaceSuggestionMaterializationRequest: placeSuggestionMaterializationRequestSchema,
  PlaceSuggestionMaterializationResponse: placeSuggestionMaterializationResponseSchema,
  ProviderPlaceDetailRequest: providerPlaceDetailRequestSchema,
  ProviderPlaceDetail: providerPlaceDetailSchema,
  ProviderCapabilityListV2: providerCapabilityListV2Schema,
  ProviderConnectionListV2: providerConnectionListV2Schema,
  ProviderConnectionCommandRequestV2: providerConnectionCommandRequestV2Schema,
  ProviderConnectionCommandResultV2: providerConnectionCommandResultV2Schema,
  ProviderTargetListProjectionV2: providerTargetListProjectionV2Schema,
  SourceSnapshotListV2: sourceSnapshotListV2Schema,
  SourceSnapshotDetailV2: sourceSnapshotDetailV2Schema,
  ImportPlanCommandRequestV2: importPlanCommandRequestV2Schema,
  ImportPlanCommandResultV2: importPlanCommandResultV2Schema,
  ImportPlanV2: importPlanV2Schema,
  OutboundTransferCommandRequestV2: outboundTransferCommandRequestV2Schema,
  OutboundTransferCommandResultV2: outboundTransferCommandResultV2Schema,
  OutboundTransferV2: outboundTransferV2Schema,
  TransferOperationV2: transferOperationV2Schema,
  TransferOperationListV2: transferOperationListV2Schema,
  TransferOperationSummaryV2: transferOperationSummaryV2Schema,
  TransferOperationItemPageV2: transferOperationItemPageV2Schema,
  TransferOperationCommandRequestV2: transferOperationCommandRequestV2Schema,
  TransferOperationCommandResultV2: transferOperationCommandResultV2Schema,
  AccountErasureReviewCommandRequestV2: accountErasureReviewCommandRequestV2Schema,
  AccountErasureReviewCommandResultV2: accountErasureReviewCommandResultV2Schema,
  ConnectorImportGrantRequestV2: connectorImportGrantRequestV2Schema,
  ConnectorImportGrantResultV2: connectorImportGrantResultV2Schema,
  ConnectorCaptureChunkV2: connectorCaptureChunkV2Schema,
  ConnectorCaptureChunkReceiptV2: connectorCaptureChunkReceiptV2Schema,
  ConnectorCaptureManifestStatusV2: connectorCaptureManifestStatusV2Schema,
  ConnectorCaptureCompleteRequestV2: connectorCaptureCompleteRequestV2Schema,
  ConnectorCaptureCompleteResultV2: connectorCaptureCompleteResultV2Schema,
  OutboundExecutionGrantRequestV2: outboundExecutionGrantRequestV2Schema,
  OutboundExecutionGrantResultV2: outboundExecutionGrantResultV2Schema,
  OutboundExecutionConsumeRequestV2: outboundExecutionConsumeRequestV2Schema,
  OutboundExecutionAuthorizationReceiptV2: outboundExecutionAuthorizationReceiptV2Schema,
  OutboundExecutionAttemptIntentV2: outboundExecutionAttemptIntentV2Schema,
  OutboundExecutionAttemptIntentReceiptV2: outboundExecutionAttemptIntentReceiptV2Schema,
  OutboundExecutionAttemptV2: outboundExecutionAttemptV2Schema,
  OutboundExecutionAttemptReceiptV2: outboundExecutionAttemptReceiptV2Schema,
  OutboundExecutionReconciliationV2: outboundExecutionReconciliationV2Schema,
  OutboundExecutionReconciliationReceiptV2: outboundExecutionReconciliationReceiptV2Schema,
  TaxonomyProjection: taxonomyProjectionSchema,
  Problem: problemSchema,
}


function openApiSchema(schema: ZodType): Record<string, unknown> {
  const generated = z.toJSONSchema(schema, { target: 'draft-2020-12', io: 'input' })
  const { $schema: _, ...component } = generated
  return component
}

const problemResponse = (description: string) => ({
  description,
  content: { 'application/problem+json': { schema: ref('schemas', 'Problem') } },
})

export function buildOpenApiDocument() {
  return {
    openapi: '3.1.0',
    info: {
      title: 'Place HTTP',
      version: '1.0.0',
      description: 'Place-owned source-only HTTP and browser BFF contract.',
    },
    servers: [],
    paths,
    components: {
      securitySchemes: {
        placeBearer: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
        placeBrowserSession: { type: 'apiKey', in: 'cookie', name: '__Host-place_session' },
        placeConnector: { type: 'http', scheme: 'PlaceConnector' },
      },
      schemas: Object.fromEntries(
        Object.entries(schemas).map(([name, schema]) => [name, openApiSchema(schema)]),
      ),
      responses: {
        ProductUnavailable: problemResponse('A required product capability is temporarily unavailable'),
        BrowserBackendUnavailable: problemResponse('The fixed internal Place Backend is temporarily unavailable'),
        ProductRequestInvalid: problemResponse('The product request is malformed or contains unsupported fields'),
        ProductNotFound: problemResponse('The owned resource or disclosed publication is unavailable'),
        PlaceRetired: problemResponse('The canonical Place was retired and has no active successor'),
        PlaceDetailUnavailable: problemResponse('The canonical Place detail projection is temporarily unavailable'),
        LibraryQueryUnavailable: problemResponse('The bounded Library query is temporarily unavailable'),
        VisitQueryUnavailable: problemResponse('The bounded Visit query is temporarily unavailable'),
        WritingQueryUnavailable: problemResponse('The bounded Writing query is temporarily unavailable'),
        ImportQueryUnavailable: problemResponse('The bounded Import query is temporarily unavailable'),
        ProductConflict: problemResponse('The request conflicts with prior state'),
        AuthenticationRequired: problemResponse('The bearer token is missing or invalid'),
        ConnectorGrantInvalid: problemResponse('The connector grant is missing, expired, or invalid'),
        AccessDenied: problemResponse('The principal lacks Place access'),
        BrowserAuthRejected: problemResponse('The browser login transaction was rejected'),
        BrowserAuthUnavailable: problemResponse('Browser authentication is inactive or unavailable'),
        BrowserMembershipUnavailable: problemResponse('Browser membership is inactive or unavailable'),
        OnboardingRequestInvalid: problemResponse('The onboarding request is invalid'),
        MembershipConsentRequired: problemResponse('Current Place consent is required'),
        MembershipOnboardingUnavailable: problemResponse('Membership onboarding is unavailable'),
        AuthorityRequestInvalid: problemResponse('The authority-role request is invalid'),
        MembershipNotFound: problemResponse('The target membership does not exist'),
        AuthorityChangeRejected: problemResponse('The authority-role change was rejected'),
        AuthorityChangeUnavailable: problemResponse('Authority-role management is unavailable'),
      },
    },
  }
}
