import { anonymous, browserSession, described, operation, ref } from '../model.js'
import {
  boundedCursorParameter,
  boundedLimitParameter,
  importBatchStateParameter,
  importItemLimitParameter,
  libraryAreaKeysParameter,
  libraryMapCollectionIdParameter,
  libraryMapScopeParameter,
  libraryMapViewportParameters,
  libraryPlaceStateParameter,
  libraryTagIdsParameter,
  libraryTagMatchParameter,
  libraryTaxonomyKeysParameter,
  pathParameters,
  personalLibraryRatingParameter,
  writingKindParameter,
  writingPlaceIdParameter,
} from '../parameters.js'

export const systemAndBrowserPaths = {
  '/healthz': { get: operation('getPlaceHealth', {
    '200': described('Process is alive', 'ProcessStatus'),
  }) },
  '/readyz': { get: operation('getPlaceReadiness', {
    '200': described('Process can accept traffic', 'ProcessStatus'),
    '503': described('One or more required process dependencies are unavailable', 'ProcessStatus'),
  }) },
  '/api/maps/style': { get: operation('getPlaceMapStyleForBrowser', {
    '200': described(
      'Return the same-origin minimal MapLibre style used by deterministic runtimes',
      'BrowserMapStyle',
    ),
  }, { security: anonymous }) },
  '/api/auth/oidc/start': { get: operation('startPlaceBrowserLogin', {
    '302': described('Redirect to the configured Identity authorization endpoint'),
    '503': ref('responses', 'BrowserAuthUnavailable'),
  }) },
  '/api/auth/oidc/callback': { get: operation('completePlaceBrowserLogin', {
    '303': described('Create an opaque browser session and redirect locally'),
    '400': ref('responses', 'BrowserAuthRejected'),
    '503': ref('responses', 'BrowserAuthUnavailable'),
  }) },
  '/api/auth/logout': { post: operation('endPlaceBrowserSession', {
    '303': described('Delete the server-side session and redirect locally'),
    '503': ref('responses', 'BrowserAuthUnavailable'),
  }) },
  '/api/admin/session': { get: operation('getCurrentPlaceAdminSession', {
    '200': described('Return the current authorized administrator session', 'AdminSession'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession }) },
  '/api/membership-consents/current': { get: operation(
    'getCurrentPlaceMembershipConsentsForBrowser',
    {
      '200': described('Return current consent versions', 'CurrentMembershipConsents'),
      '503': ref('responses', 'BrowserMembershipUnavailable'),
    },
    { security: anonymous },
  ) },
  '/api/memberships/onboarding': { post: operation(
    'completePlaceBrowserMembershipOnboarding',
    {
      '200': described('Return the existing membership', 'MembershipOnboardingResult'),
      '201': described('Create a non-elevated membership', 'MembershipOnboardingResult'),
      '400': ref('responses', 'OnboardingRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '409': ref('responses', 'MembershipConsentRequired'),
      '503': ref('responses', 'BrowserMembershipUnavailable'),
    },
    { security: anonymous, requestSchema: 'MembershipOnboardingRequest' },
  ) },
  '/api/places/{placeId}': {
    parameters: [pathParameters.placeId],
    get: operation('getPlaceDetailForBrowser', {
      '200': described('Return Place detail with the requesting member personal state', 'PlaceDetailResponse'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '404': ref('responses', 'ProductNotFound'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, { security: browserSession }),
  },
  '/api/public/places/{placeId}': {
    parameters: [pathParameters.placeId],
    get: operation('getPublicPlaceDetailForBrowser', {
      '200': described('Return allowlisted anonymous Place detail', 'PublicPlaceDetailResponse'),
      '404': ref('responses', 'ProductNotFound'),
      '410': ref('responses', 'PlaceRetired'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, { security: anonymous }),
  },
  '/api/places/{placeId}/visits': {
    parameters: [pathParameters.placeId],
    get: operation('listCurrentMemberPlaceVisitsForBrowser', {
      '200': described('Return a bounded current-member Visit history', 'VisitHistoryResponse'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, {
      security: browserSession,
      parameters: [boundedCursorParameter, boundedLimitParameter],
    }),
  },
  '/api/visits': { post: operation('recordPlaceVisitForBrowser', {
    '201': described('Record or replay an immutable Visit occurrence', 'VisitRecordResult'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '409': ref('responses', 'ProductConflict'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession, requestSchema: 'BrowserVisitRecordRequest' }) },
  '/api/writing': {
    get: operation('listCurrentMemberPlaceWritingForBrowser', {
      '200': described('Return bounded current-member Writing summaries', 'WritingListResponse'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, {
      security: browserSession,
      parameters: [writingKindParameter, writingPlaceIdParameter, boundedCursorParameter, boundedLimitParameter],
    }),
  },
  '/api/writing/{documentId}': {
    parameters: [pathParameters.documentId],
    get: operation('getCurrentMemberPlaceWritingForBrowser', {
      '200': described('Return current-member Writing detail', 'WritingDetailResponse'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '404': ref('responses', 'ProductNotFound'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, { security: browserSession }),
  },
  '/api/writing/commands': { post: operation('applyPrivateNoteCommandForBrowser', {
    '200': described('Return an idempotently replayed private Note command', 'WritingCommandResult'),
    '201': described('Return an applied private Note command', 'WritingCommandResult'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '404': ref('responses', 'ProductNotFound'),
    '409': ref('responses', 'ProductConflict'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession, requestSchema: 'BrowserPrivateNoteCommandRequest' }) },
  '/api/library/places': { get: operation('listPlaceLibraryPlacesForBrowser', {
    '200': described('Return a bounded member Place preference page', 'LibraryPlaceListResponse'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, {
    security: browserSession,
    parameters: [
      libraryPlaceStateParameter,
      libraryTagIdsParameter,
      libraryTagMatchParameter,
      libraryAreaKeysParameter,
      libraryTaxonomyKeysParameter,
      boundedCursorParameter,
      boundedLimitParameter,
    ],
  }) },
  '/api/library/map': { get: operation('getPlaceLibraryMapForBrowser', {
    '200': described('Represent every projected member Place in the current viewport as a point or cluster', 'LibraryMapResponse'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '404': ref('responses', 'ProductNotFound'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, {
    security: browserSession,
    parameters: [
      libraryMapScopeParameter,
      libraryMapCollectionIdParameter,
      libraryPlaceStateParameter,
      libraryTagIdsParameter,
      libraryTagMatchParameter,
      libraryAreaKeysParameter,
      libraryTaxonomyKeysParameter,
      ...libraryMapViewportParameters,
    ],
  }) },
  '/api/library/place-facets': { get: operation('getPlaceLibraryFacetsForBrowser', {
    '200': described('Return bounded area and taxonomy facets from the member saved Places', 'LibraryPlaceFacetsResponse'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession }) },
  '/api/library/places/{placeId}/organization': {
    parameters: [pathParameters.placeId],
    get: operation('getPlaceLibraryOrganizationForBrowser', {
      '200': described(
        'Return bounded current-member Collection and Tag choices with selection state for one Place',
        'LibraryPlaceOrganizationResponse',
      ),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, {
      security: browserSession,
      parameters: [boundedCursorParameter, boundedLimitParameter],
    }),
  },
  '/api/library/collections': { get: operation('listPlaceLibraryCollectionsForBrowser', {
    '200': described('Return a bounded member Collection page', 'LibraryCollectionListResponse'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, {
    security: browserSession,
    parameters: [boundedCursorParameter, boundedLimitParameter],
  }) },
  '/api/library/collections/{collectionId}': {
    parameters: [pathParameters.collectionId],
    get: operation('getPlaceLibraryCollectionForBrowser', {
      '200': described('Return Collection metadata and a bounded Place page', 'LibraryCollectionDetailResponse'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '404': ref('responses', 'ProductNotFound'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, {
      security: browserSession,
      parameters: [boundedCursorParameter, boundedLimitParameter],
    }),
  },
  '/api/library/tags': { get: operation('listPlaceLibraryTagsForBrowser', {
    '200': described('Return a bounded member Tag page', 'LibraryTagListResponse'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, {
    security: browserSession,
    parameters: [boundedCursorParameter, boundedLimitParameter],
  }) },
  '/api/library/commands': { post: operation('applyPlaceLibraryCommandForBrowser', {
    '200': described('Return an idempotently replayed command result', 'LibraryCommandResult'),
    '201': described('Return an applied command result', 'LibraryCommandResult'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '404': ref('responses', 'ProductNotFound'),
    '409': ref('responses', 'ProductConflict'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession, requestSchema: 'BrowserLibraryCommandRequest' }) },
  '/api/imports/connections': { get: operation('listPlaceProviderConnectionsForBrowser', {
    '200': described('Return sanitized provider connection metadata', 'ProviderConnectionList'),
    '401': ref('responses', 'AuthenticationRequired'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession }) },
  '/api/imports': { post: operation('requestPlaceImportForBrowser', {
    '200': described('Return an idempotently replayed import batch', 'PlaceImportBatch'),
    '202': described('Queue a connected-account import', 'PlaceImportBatch'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '409': ref('responses', 'ProductConflict'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession, requestSchema: 'PlaceImportRequest' }) },
  '/api/imports/{batchId}': {
    parameters: [pathParameters.batchId],
    get: operation('getPlaceImportForBrowser', {
      '200': described('Return a bounded import preview and progress', 'PlaceImportBatchDetail'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '404': ref('responses', 'ProductNotFound'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, {
      security: browserSession,
      parameters: [boundedCursorParameter, importItemLimitParameter],
    }),
  },
  '/api/imports/{batchId}/cancel': {
    parameters: [pathParameters.batchId],
    post: operation('cancelPlaceImportForBrowser', {
      '200': described('Return the cancelled import batch', 'PlaceImportBatch'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '404': ref('responses', 'ProductNotFound'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, { security: browserSession, requestSchema: 'PlaceImportCancelRequest' }),
  },
  '/api/imports/{batchId}/resume': {
    parameters: [pathParameters.batchId],
    post: operation('resumePlaceImportForBrowser', {
      '200': described('Return the resumed import batch', 'PlaceImportBatch'),
      '400': ref('responses', 'ProductRequestInvalid'),
      '401': ref('responses', 'AuthenticationRequired'),
      '403': ref('responses', 'AccessDenied'),
      '404': ref('responses', 'ProductNotFound'),
      '503': ref('responses', 'BrowserBackendUnavailable'),
    }, { security: browserSession, requestSchema: 'PlaceImportResumeRequest' }),
  },
  '/api/import-reviews': { post: operation('reviewPlaceImportItemForBrowser', {
    '200': described('Return an idempotent import review receipt', 'PlaceImportReviewResult'),
    '400': ref('responses', 'ProductRequestInvalid'),
    '401': ref('responses', 'AuthenticationRequired'),
    '403': ref('responses', 'AccessDenied'),
    '404': ref('responses', 'ProductNotFound'),
    '409': ref('responses', 'ProductConflict'),
    '503': ref('responses', 'BrowserBackendUnavailable'),
  }, { security: browserSession, requestSchema: 'PlaceImportReviewRequest' }) },
}
