import type { TaxonomyNodeVersion } from '../../domain/model.js'

// Product-owned vocabulary, not a provider mapping or a member Collection.
const definitions = [
  ["food",null,"음식점"],
  ["food.korean","food","한식"],
  ["food.japanese","food","일식"],
  ["food.chinese","food","중식"],
  ["food.western","food","양식"],
  ["food.asian","food","아시아 음식"],
  ["food.snack","food","분식"],
  ["food.fast","food","패스트푸드"],
  ["food.noodle.ramen","food.japanese","라멘"],
  ["food.noodle.ramen.shoyu","food.noodle.ramen","쇼유라멘"],
  ["food.noodle.ramen.shio","food.noodle.ramen","시오라멘"],
  ["food.noodle.ramen.miso","food.noodle.ramen","미소라멘"],
  ["food.noodle.ramen.tonkotsu","food.noodle.ramen","돈코츠라멘"],
  ["food.japanese.sushi","food.japanese","초밥"],
  ["food.japanese.udon","food.japanese","우동"],
  ["food.japanese.soba","food.japanese","소바"],
  ["food.japanese.tonkatsu","food.japanese","돈카츠"],
  ["drink",null,"카페·음료"],
  ["drink.coffee","drink","카페"],
  ["drink.tea","drink","찻집"],
  ["drink.bakery","drink","베이커리"],
  ["drink.dessert","drink","디저트"],
  ["tourism",null,"관광지"],
  ["tourism.park","tourism","공원"],
  ["tourism.nature","tourism","자연명소"],
  ["tourism.historic","tourism","역사유적"],
  ["shopping",null,"쇼핑"],
  ["shopping.market","shopping","시장"],
  ["shopping.mall","shopping","쇼핑몰"],
  ["shopping.bookstore","shopping","서점"],
  ["culture",null,"문화시설"],
  ["culture.museum","culture","박물관"],
  ["culture.gallery","culture","미술관"],
  ["culture.performance","culture","공연장"],
  ["culture.library","culture","도서관"],
  ["lodging",null,"숙박"],
  ["lodging.hotel","lodging","호텔"],
  ["lodging.guesthouse","lodging","게스트하우스"],
  ["lodging.camping","lodging","캠핑장"],
  ["leisure",null,"운동·여가"],
  ["leisure.sports","leisure","체육시설"],
  ["leisure.recreation","leisure","놀이시설"],
  ["services",null,"생활서비스"],
  ["services.health","services","의료기관"],
  ["services.public","services","공공기관"],
] as const

export const productTaxonomyNodes: readonly TaxonomyNodeVersion[] = definitions.map(([key, parentKey, label]) => ({
  key, parentKey, label, kind: 'category', version: 1, active: true, effectiveAt: '2026-09-06T00:00:00.000Z',
}))
